-- V1__criar_usuarios.sql
-- Contexto: usuário

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,
    data_admissao DATE NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_usuarios_nome_nao_vazio
        CHECK (BTRIM(nome) <> ''),

    CONSTRAINT ck_usuarios_email_nao_vazio
        CHECK (BTRIM(email) <> ''),

    CONSTRAINT ck_usuarios_perfil
        CHECK (perfil IN ('ADMIN', 'RESPONSAVEL', 'CANDIDATO'))
);

-- Impede e-mails duplicados desconsiderando letras maiúsculas/minúsculas.
CREATE UNIQUE INDEX uk_usuarios_email_normalizado
    ON usuarios (LOWER(email));

CREATE INDEX idx_usuarios_perfil
    ON usuarios (perfil);

CREATE INDEX idx_usuarios_ativo
    ON usuarios (ativo);

COMMENT ON TABLE usuarios IS
    'Colaboradores que acessam a plataforma de recrutamento interno.';

COMMENT ON COLUMN usuarios.senha_hash IS
    'Senha codificada com BCrypt; nunca armazenar a senha em texto puro.';


-- Atualiza automaticamente o campo atualizado_em.
CREATE OR REPLACE FUNCTION definir_atualizado_em()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.atualizado_em = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_usuarios_definir_atualizado_em
BEFORE UPDATE ON usuarios
FOR EACH ROW
EXECUTE FUNCTION definir_atualizado_em();
