-- V2__criar_vagas_e_requisitos.sql
-- Contexto: vaga

CREATE TABLE vagas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RASCUNHO',
    responsavel_id BIGINT NOT NULL,
    data_limite DATE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vagas_responsavel
        FOREIGN KEY (responsavel_id)
        REFERENCES usuarios (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_vagas_titulo_nao_vazio
        CHECK (BTRIM(titulo) <> ''),

    CONSTRAINT ck_vagas_descricao_nao_vazia
        CHECK (BTRIM(descricao) <> ''),

    CONSTRAINT ck_vagas_status
        CHECK (status IN ('RASCUNHO', 'ABERTA', 'ENCERRADA', 'CANCELADA'))
);

CREATE INDEX idx_vagas_status
    ON vagas (status);

CREATE INDEX idx_vagas_responsavel
    ON vagas (responsavel_id);

CREATE INDEX idx_vagas_data_limite
    ON vagas (data_limite);

-- Auxilia a busca textual simples com ILIKE.
CREATE INDEX idx_vagas_titulo_lower
    ON vagas (LOWER(titulo));


CREATE TABLE requisitos_vaga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    tipo VARCHAR(40) NOT NULL,
    valor_texto VARCHAR(255),
    valor_numerico INTEGER,
    obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_requisitos_vaga
        FOREIGN KEY (vaga_id)
        REFERENCES vagas (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT ck_requisitos_nome_nao_vazio
        CHECK (BTRIM(nome) <> ''),

    CONSTRAINT ck_requisitos_tipo
        CHECK (
            tipo IN (
                'COMPETENCIA',
                'TEMPO_EMPRESA_MESES',
                'OUTRO'
            )
        ),

    CONSTRAINT ck_requisitos_valor_numerico_nao_negativo
        CHECK (valor_numerico IS NULL OR valor_numerico >= 0),

    CONSTRAINT ck_requisitos_tempo_empresa
        CHECK (
            tipo <> 'TEMPO_EMPRESA_MESES'
            OR valor_numerico IS NOT NULL
        )
);

CREATE INDEX idx_requisitos_vaga_vaga
    ON requisitos_vaga (vaga_id);

CREATE INDEX idx_requisitos_vaga_tipo
    ON requisitos_vaga (tipo);

CREATE INDEX idx_requisitos_vaga_nome_lower
    ON requisitos_vaga (LOWER(nome));


CREATE TRIGGER trg_vagas_definir_atualizado_em
BEFORE UPDATE ON vagas
FOR EACH ROW
EXECUTE FUNCTION definir_atualizado_em();

COMMENT ON TABLE vagas IS
    'Vagas internas cadastradas por administradores ou responsáveis.';

COMMENT ON TABLE requisitos_vaga IS
    'Requisitos associados a uma vaga, inclusive tempo mínimo de empresa.';
