-- V3__criar_candidaturas_e_historico.sql
-- Contexto: candidatura

CREATE TABLE candidaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id BIGINT NOT NULL,
    candidato_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ENVIADA',
    mensagem VARCHAR(1000),
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_candidaturas_vaga
        FOREIGN KEY (vaga_id)
        REFERENCES vagas (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_candidaturas_candidato
        FOREIGN KEY (candidato_id)
        REFERENCES usuarios (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uk_candidaturas_vaga_candidato
        UNIQUE (vaga_id, candidato_id),

    CONSTRAINT ck_candidaturas_status
        CHECK (
            status IN (
                'ENVIADA',
                'EM_ANALISE',
                'APROVADA',
                'REPROVADA',
                'RETIRADA'
            )
        )
);

CREATE INDEX idx_candidaturas_vaga
    ON candidaturas (vaga_id);

CREATE INDEX idx_candidaturas_candidato
    ON candidaturas (candidato_id);

CREATE INDEX idx_candidaturas_status
    ON candidaturas (status);

CREATE INDEX idx_candidaturas_vaga_status
    ON candidaturas (vaga_id, status);


CREATE TABLE historico_status_candidatura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidatura_id BIGINT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    comentario VARCHAR(1000),
    alterado_por_id BIGINT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_historico_candidatura
        FOREIGN KEY (candidatura_id)
        REFERENCES candidaturas (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT fk_historico_alterado_por
        FOREIGN KEY (alterado_por_id)
        REFERENCES usuarios (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_historico_status_anterior
        CHECK (
            status_anterior IS NULL
            OR status_anterior IN (
                'ENVIADA',
                'EM_ANALISE',
                'APROVADA',
                'REPROVADA',
                'RETIRADA'
            )
        ),

    CONSTRAINT ck_historico_status_novo
        CHECK (
            status_novo IN (
                'ENVIADA',
                'EM_ANALISE',
                'APROVADA',
                'REPROVADA',
                'RETIRADA'
            )
        ),

    CONSTRAINT ck_historico_status_diferentes
        CHECK (
            status_anterior IS NULL
            OR status_anterior <> status_novo
        )
);

CREATE INDEX idx_historico_candidatura
    ON historico_status_candidatura (candidatura_id);

CREATE INDEX idx_historico_candidatura_data
    ON historico_status_candidatura (candidatura_id, criado_em);


CREATE TRIGGER trg_candidaturas_definir_atualizado_em
BEFORE UPDATE ON candidaturas
FOR EACH ROW
EXECUTE FUNCTION definir_atualizado_em();

COMMENT ON TABLE candidaturas IS
    'Registro da candidatura de um colaborador para uma vaga.';

COMMENT ON CONSTRAINT uk_candidaturas_vaga_candidato ON candidaturas IS
    'Garante idempotência e impede duas candidaturas do mesmo usuário para a mesma vaga.';

COMMENT ON TABLE historico_status_candidatura IS
    'Histórico imutável das transições de status de cada candidatura.';
