-- V4__criar_avaliacoes.sql
-- Contexto: candidatura / avaliação

CREATE TABLE avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidatura_id BIGINT NOT NULL,
    avaliador_id BIGINT NOT NULL,
    nota SMALLINT NOT NULL,
    parecer VARCHAR(2000) NOT NULL,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_avaliacoes_candidatura
        FOREIGN KEY (candidatura_id)
        REFERENCES candidaturas (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT fk_avaliacoes_avaliador
        FOREIGN KEY (avaliador_id)
        REFERENCES usuarios (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uk_avaliacoes_candidatura
        UNIQUE (candidatura_id),

    CONSTRAINT ck_avaliacoes_nota
        CHECK (nota BETWEEN 1 AND 5),

    CONSTRAINT ck_avaliacoes_parecer_nao_vazio
        CHECK (BTRIM(parecer) <> '')
);

CREATE INDEX idx_avaliacoes_avaliador
    ON avaliacoes (avaliador_id);


CREATE TRIGGER trg_avaliacoes_definir_atualizado_em
BEFORE UPDATE ON avaliacoes
FOR EACH ROW
EXECUTE FUNCTION definir_atualizado_em();

COMMENT ON TABLE avaliacoes IS
    'Avaliação registrada pelo responsável ou administrador para uma candidatura.';
