-- V5__criar_notificacoes.sql
-- Contexto: notificação

CREATE TABLE notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    mensagem VARCHAR(1000) NOT NULL,
    lida BOOLEAN NOT NULL DEFAULT FALSE,
    vaga_id BIGINT,
    candidatura_id BIGINT,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notificacoes_destinatario
        FOREIGN KEY (destinatario_id)
        REFERENCES usuarios (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT fk_notificacoes_vaga
        FOREIGN KEY (vaga_id)
        REFERENCES vagas (id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,

    CONSTRAINT fk_notificacoes_candidatura
        FOREIGN KEY (candidatura_id)
        REFERENCES candidaturas (id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,

    CONSTRAINT ck_notificacoes_tipo
        CHECK (
            tipo IN (
                'CANDIDATURA_RECEBIDA',
                'STATUS_ALTERADO',
                'FEEDBACK_RECEBIDO'
            )
        ),

    CONSTRAINT ck_notificacoes_titulo_nao_vazio
        CHECK (BTRIM(titulo) <> ''),

    CONSTRAINT ck_notificacoes_mensagem_nao_vazia
        CHECK (BTRIM(mensagem) <> ''),

    CONSTRAINT ck_notificacoes_referencia_unica
        CHECK (vaga_id IS NULL OR candidatura_id IS NULL)
);

CREATE INDEX idx_notificacoes_destinatario
    ON notificacoes (destinatario_id);

CREATE INDEX idx_notificacoes_destinatario_lida
    ON notificacoes (destinatario_id, lida);

CREATE INDEX idx_notificacoes_criada_em
    ON notificacoes (criada_em DESC);

CREATE INDEX idx_notificacoes_vaga
    ON notificacoes (vaga_id);

CREATE INDEX idx_notificacoes_candidatura
    ON notificacoes (candidatura_id);

COMMENT ON TABLE notificacoes IS
    'Notificações persistidas para colaboradores e responsáveis.';
