-- V6__criar_competencias_e_associacoes.sql
-- Contexto: competencia

CREATE TABLE competencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_competencias_nome_nao_vazio
        CHECK (BTRIM(nome) <> '')
);

CREATE UNIQUE INDEX uk_competencias_nome_normalizado
    ON competencias (LOWER(nome));

CREATE INDEX idx_competencias_ativa
    ON competencias (ativa);

CREATE TRIGGER trg_competencias_definir_atualizado_em
BEFORE UPDATE ON competencias
FOR EACH ROW
EXECUTE FUNCTION definir_atualizado_em();


CREATE TABLE usuarios_competencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    competencia_id BIGINT NOT NULL,
    nivel VARCHAR(30) NOT NULL,
    meses_experiencia INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_usuarios_competencias_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT fk_usuarios_competencias_competencia
        FOREIGN KEY (competencia_id)
        REFERENCES competencias (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uk_usuarios_competencias_usuario_competencia
        UNIQUE (usuario_id, competencia_id),

    CONSTRAINT ck_usuarios_competencias_nivel
        CHECK (nivel IN ('BASICO', 'INTERMEDIARIO', 'AVANCADO')),

    CONSTRAINT ck_usuarios_competencias_meses
        CHECK (meses_experiencia >= 0)
);

CREATE INDEX idx_usuarios_competencias_usuario
    ON usuarios_competencias (usuario_id);

CREATE INDEX idx_usuarios_competencias_competencia
    ON usuarios_competencias (competencia_id);


CREATE TABLE vagas_competencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id BIGINT NOT NULL,
    competencia_id BIGINT NOT NULL,
    nivel_minimo VARCHAR(30) NOT NULL,
    meses_experiencia_minima INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_vagas_competencias_vaga
        FOREIGN KEY (vaga_id)
        REFERENCES vagas (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT fk_vagas_competencias_competencia
        FOREIGN KEY (competencia_id)
        REFERENCES competencias (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uk_vagas_competencias_vaga_competencia
        UNIQUE (vaga_id, competencia_id),

    CONSTRAINT ck_vagas_competencias_nivel
        CHECK (nivel_minimo IN ('BASICO', 'INTERMEDIARIO', 'AVANCADO')),

    CONSTRAINT ck_vagas_competencias_meses
        CHECK (meses_experiencia_minima >= 0)
);

CREATE INDEX idx_vagas_competencias_vaga
    ON vagas_competencias (vaga_id);

CREATE INDEX idx_vagas_competencias_competencia
    ON vagas_competencias (competencia_id);


-- Converte os requisitos textuais antigos em competências do catálogo.
INSERT INTO competencias (nome)
SELECT MIN(BTRIM(nome))
FROM requisitos_vaga
WHERE tipo = 'COMPETENCIA'
GROUP BY LOWER(BTRIM(nome))
ON CONFLICT DO NOTHING;

WITH requisitos_normalizados AS (
    SELECT
        requisito.vaga_id,
        competencia.id AS competencia_id,
        MAX(
            CASE UPPER(BTRIM(COALESCE(requisito.valor_texto, '')))
                WHEN 'AVANCADO' THEN 3
                WHEN 'AVANÇADO' THEN 3
                WHEN 'INTERMEDIARIO' THEN 2
                WHEN 'INTERMEDIÁRIO' THEN 2
                ELSE 1
            END
        ) AS ordem_nivel,
        MAX(COALESCE(requisito.valor_numerico, 0)) AS meses_experiencia_minima
    FROM requisitos_vaga requisito
    JOIN competencias competencia
        ON LOWER(competencia.nome) = LOWER(BTRIM(requisito.nome))
    WHERE requisito.tipo = 'COMPETENCIA'
    GROUP BY requisito.vaga_id, competencia.id
)
INSERT INTO vagas_competencias (
    vaga_id,
    competencia_id,
    nivel_minimo,
    meses_experiencia_minima
)
SELECT
    vaga_id,
    competencia_id,
    CASE ordem_nivel
        WHEN 3 THEN 'AVANCADO'
        WHEN 2 THEN 'INTERMEDIARIO'
        ELSE 'BASICO'
    END,
    meses_experiencia_minima
FROM requisitos_normalizados;

DELETE FROM requisitos_vaga
WHERE tipo = 'COMPETENCIA';

ALTER TABLE requisitos_vaga
    DROP CONSTRAINT ck_requisitos_tipo;

ALTER TABLE requisitos_vaga
    ADD CONSTRAINT ck_requisitos_tipo
        CHECK (tipo IN ('TEMPO_EMPRESA_MESES', 'OUTRO'));

COMMENT ON TABLE competencias IS
    'Catálogo global de competências disponíveis para usuários e vagas.';

COMMENT ON TABLE usuarios_competencias IS
    'Competências declaradas pelo usuário, com nível e tempo de experiência.';

COMMENT ON TABLE vagas_competencias IS
    'Competências necessárias para a vaga, com nível e experiência mínimos.';
