-- V7__criar_organizacoes.sql
-- Contexto: organizacao

CREATE TABLE organizacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_organizacoes_nome_nao_vazio
        CHECK (BTRIM(nome) <> '')
);

CREATE UNIQUE INDEX uk_organizacoes_nome_normalizado
    ON organizacoes (LOWER(nome));

CREATE INDEX idx_organizacoes_ativa
    ON organizacoes (ativa);

CREATE TRIGGER trg_organizacoes_definir_atualizado_em
BEFORE UPDATE ON organizacoes
FOR EACH ROW
EXECUTE FUNCTION definir_atualizado_em();

-- Preserva usuários existentes atribuindo-os a uma organização de transição.
INSERT INTO organizacoes (nome)
VALUES ('Organização padrão');

ALTER TABLE usuarios
    ADD COLUMN organizacao_id BIGINT;

UPDATE usuarios
SET organizacao_id = (
    SELECT id
    FROM organizacoes
    WHERE nome = 'Organização padrão'
);

ALTER TABLE usuarios
    ALTER COLUMN organizacao_id SET NOT NULL,
    ADD CONSTRAINT fk_usuarios_organizacao
        FOREIGN KEY (organizacao_id)
        REFERENCES organizacoes (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    ADD CONSTRAINT uk_usuarios_id_organizacao
        UNIQUE (id, organizacao_id);

CREATE INDEX idx_usuarios_organizacao
    ON usuarios (organizacao_id);

ALTER TABLE vagas
    ADD COLUMN organizacao_id BIGINT;

UPDATE vagas vaga
SET organizacao_id = usuario.organizacao_id
FROM usuarios usuario
WHERE usuario.id = vaga.responsavel_id;

ALTER TABLE vagas
    ALTER COLUMN organizacao_id SET NOT NULL,
    DROP CONSTRAINT fk_vagas_responsavel,
    ADD CONSTRAINT fk_vagas_organizacao
        FOREIGN KEY (organizacao_id)
        REFERENCES organizacoes (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    ADD CONSTRAINT fk_vagas_responsavel_organizacao
        FOREIGN KEY (responsavel_id, organizacao_id)
        REFERENCES usuarios (id, organizacao_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT;

CREATE INDEX idx_vagas_organizacao
    ON vagas (organizacao_id);

COMMENT ON TABLE organizacoes IS
    'Empresas que agrupam usuários responsáveis e suas vagas.';

COMMENT ON CONSTRAINT fk_vagas_responsavel_organizacao ON vagas IS
    'Garante que a vaga pertença à mesma organização de seu responsável.';
